bot:
  prefix: ""
  production: false # if false, version number will have "b" (beta) appended to it
  feedback: 0 # channel ID for feedback
api:
  enabled: true # mostly useless for selfhosting but u can keep it on if u want
  port: 6142
rethinkdb:
  host: "localhost" # host of rethinkdb. usually localhost
  port: 28015 # port of rethinkdb. usually 28015
integrations:
  osu: true # osu commands
  openweathermap: true # weather command
  botlists: false # show server count on botlists - useless for selfhost
  wolfram: true # wolframalpha command
  whois: true # whois command
  weeb: true # weebsh stuff idk
tokens:
  discord: "discord token" # required
  openweathermap: "owm api key" # openweathermap.org just sign up
  osu: "osu api key" # osu.ppy.sh/p/api
  topgg: "top.gg api key" # ur not getting this lol
  dbots: "discord.bots.gg api key" # ur not getting this lol
  wa: "wolframalpha api key" # products.wolframalpha.com/api, sign up to get key
  whois: "whoisxmlapi.com api key" # whois.whoisxmlapi.com, sign up to get key
  weeb: "weeb.sh api key" # lets just face it ur not getting this either